### ISSUE TITLE
Fail to press Run/Debug (F5) to run in debugger under `http` path

### ISSUE THREAD

**Issue by v-weiyding** [Azure-Samples/azure-functions-java-flex-consumption-azd#8]
**Describe the issue:**
When press Run/Debug (F5) in the `http` path, there is no debugger configured, and the page is as follows:
 
![image](https://github.com/user-attachments/assets/63164698-0a09-4cce-aea0-b5dce39a6f4d)

![image](https://github.com/user-attachments/assets/debcf2e5-aa86-47e9-a894-4889862e8486)

**Repro Steps:**

1. Run `azd init --template azure-functions-java-flex-consumption-azd`.
2. Run `azd auth login`.
3. Run `azd up`.
4. Run `cd ./http`.
5. Run `code .`.
6. Press F5.

**Expected behavior:**
Press Run/Debug (F5) to run successfully.

@hemarina and @BigMorty for notification.

**Comment by BigMorty** [comment]
Could not repro this, F5 worked fine for me. I will say, getting your Java dev environment configured correctly is challenging.

**Comment by v-weiyding** [comment]
@BigMorty When in the project root directory, we can Run/Debug (F5) to start the debugger. 
![image](https://github.com/user-attachments/assets/3a5317a5-cabb-4b2e-9eb7-bb14c8eed5c9)

However, following the steps in the README to set the `http` folder as the root directory, it fails to Run/Debug (F5) because there are no relevant configuration files in the `.vscode` folder.

**Comment by BigMorty** [comment]
Thanks @v-weiyding for the additional details. Yes, I see the issue here. I have updated the readme so it does *not* instruct the user to change to the http directory when opening/F5ing in VSCode. Fixed by https://github.com/Azure-Samples/azure-functions-java-flex-consumption-azd/pull/11

**Comment by v-weiyding** [comment]
@BigMorty This issue has been fixed, and I will close it once the PR #11 is merged.
