### ISSUE TITLE
Links error in README.md

### ISSUE THREAD

**Issue by v-weiyding** [Azure-Samples/azure-functions-java-flex-consumption-azd#9]
**Describe the issue:**
In the [README.md](https://github.com/Azure-Samples/azure-functions-java-flex-consumption-azd?tab=readme-ov-file#run-your-app-from-the-terminal), when click `testdata.json`, the link leads to a 404 page:
![image](https://github.com/user-attachments/assets/23794d2b-62da-4935-b088-dc3994081034)
![image](https://github.com/user-attachments/assets/f4d99a65-5041-461d-90a2-a3916655932c)

**Suggestion:**
Update the link of `testdata.json` to
https://github.com/Azure-Samples/azure-functions-java-flex-consumption-azd/blob/main/http/src/testdata.json

@hemarina and @BigMorty for notification.

**Comment by BigMorty** [comment]
Fixed by https://github.com/Azure-Samples/azure-functions-java-flex-consumption-azd/pull/10
